# Generated by Django 4.2.6 on 2023-11-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraudit',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('modified', 'Modified')], default='modified', max_length=50, verbose_name='Action'),
        ),
    ]
