# Generated by Django 4.2.6 on 2023-11-16 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('object_id', models.CharField(max_length=50, verbose_name='Object ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('deleted', 'Deleted')], default='created', max_length=25, verbose_name='Action')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_89022b_idx')],
            },
        ),
    ]
